# Generated by Django 5.2.17 on 2026-09-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Job role title, e.g. 'Senior Elevator Installation Engineer'", max_length=180)),
                ('slug', models.SlugField(help_text='SEO URL slug', max_length=200, unique=True)),
                ('department', models.CharField(choices=[('Installation & Erection', 'Installation & Field Erection'), ('Maintenance & AMC', 'Service, AMC & Maintenance'), ('Engineering & Design', 'Engineering, Hoistway CAD & Design'), ('Quality & Safety Inspection', 'Quality Assurance & Safety Inspection'), ('Technical Sales & Estimation', 'Technical Sales & Estimation'), ('Manufacturing & Factory Operations', 'Manufacturing & Factory Operations'), ('Administration & Accounts', 'Corporate HR, Administration & Accounts')], db_index=True, max_length=100)),
                ('location', models.CharField(help_text="Work location, e.g. 'Ahmedabad (GIDC Works)', 'Mumbai', 'Pune', 'Surat'", max_length=120)),
                ('employment_type', models.CharField(choices=[('Full-Time Permanent', 'Full-Time Permanent'), ('Contractual', 'Contractual Project Basis'), ('Apprenticeship / Trainee', 'Apprenticeship / Graduate Trainee')], default='Full-Time Permanent', max_length=60)),
                ('experience_required', models.CharField(help_text="e.g. '3 - 5 Years in Lift / Elevator Industry'", max_length=80)),
                ('education', models.CharField(blank=True, help_text="e.g. 'ITI / Diploma / B.E. Mechanical or Electrical'", max_length=120)),
                ('number_of_vacancies', models.PositiveIntegerField(default=1, help_text='Total open positions')),
                ('description', models.TextField(help_text='Role summary, department context, and reporting hierarchy')),
                ('responsibilities', models.TextField(help_text='Key responsibilities and daily tasks (one bullet per line)')),
                ('requirements', models.TextField(help_text='Skills, lift technical knowledge, certifications required (one per line)')),
                ('benefits', models.TextField(blank=True, help_text='Compensation perks, PF/ESIC, performance incentives (one per line)')),
                ('is_urgent', models.BooleanField(default=False, help_text="Highlight with 'Urgent Hiring' badge")),
                ('active', models.BooleanField(default=True, help_text='Visible for applications on careers page')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(help_text='Full Name of candidate', max_length=120)),
                ('email', models.EmailField(help_text='Email Address', max_length=254)),
                ('phone', models.CharField(help_text='Mobile Number', max_length=25)),
                ('current_city', models.CharField(help_text='Current residential city', max_length=100)),
                ('years_of_experience', models.CharField(help_text="e.g. '4.5 Years', 'Fresher'", max_length=50)),
                ('current_company', models.CharField(blank=True, help_text='Current / Most Recent Employer', max_length=150)),
                ('resume', models.FileField(help_text='Upload CV/Resume in PDF, DOC, or DOCX format (Max 5MB)', upload_to='resumes/%Y/%m/')),
                ('cover_note', models.TextField(blank=True, help_text='Brief candidate intro or elevator industry projects handled')),
                ('status', models.CharField(choices=[('New', 'New Application'), ('Under Review', 'Under Technical Review'), ('Shortlisted', 'Shortlisted for Interview'), ('Interview Scheduled', 'Interview Scheduled'), ('Offered', 'Job Offer Made'), ('Rejected', 'Not Selected / Archive')], db_index=True, default='New', max_length=40)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal HR feedback, interview dates, salary expectations')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.jobopening')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
