# Generated by Django 5.2.17 on 2026-09-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Project title, e.g. 'Skyline Heights Twin Towers'", max_length=180)),
                ('slug', models.SlugField(help_text='SEO slug', max_length=190, unique=True)),
                ('client_name', models.CharField(blank=True, help_text='Client or Developer name', max_length=150)),
                ('location', models.CharField(help_text="Locality/Address, e.g. 'SG Highway, Bodakdev'", max_length=200)),
                ('city', models.CharField(db_index=True, help_text='e.g. Ahmedabad, Surat, Vadodara, Mumbai', max_length=100)),
                ('project_type', models.CharField(choices=[('Residential', 'Residential High-Rise & Villas'), ('Commercial', 'Commercial & Corporate Towers'), ('Healthcare', 'Hospitals & Healthcare Facilities'), ('Hospitality', 'Hotels & Luxury Resorts'), ('Industrial', 'Industrial Plants & Warehouses'), ('Infrastructure', 'Infrastructure & Public Sector')], db_index=True, max_length=50)),
                ('elevator_type', models.CharField(choices=[('Passenger Elevator', 'Passenger Elevator'), ('MRL Elevator', 'Machine Room-Less (MRL) Elevator'), ('Hospital Stretcher Elevator', 'Hospital Stretcher Elevator'), ('Freight / Goods Elevator', 'Freight / Goods Elevator'), ('Panoramic Glass Elevator', 'Panoramic Glass Elevator'), ('Hydraulic Elevator', 'Hydraulic Elevator'), ('Home / Villa Elevator', 'Home / Villa Elevator'), ('Escalator', 'Commercial Escalator')], db_index=True, max_length=60)),
                ('number_of_elevators', models.PositiveIntegerField(default=1, help_text='Total number of lift units installed')),
                ('description', models.TextField(help_text='Project case study narrative, technical challenges, and solutions delivered')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/featured/')),
                ('completion_date', models.DateField(blank=True, help_text='Commissioning / handover date', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Showcase on homepage')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
