# Generated by Django 5.2.17 on 2026-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Advanced German Technology, Uncompromising Safety', max_length=150)),
                ('description', models.TextField(help_text='Concise description highlighting engineering precision and reliability')),
                ('icon', models.CharField(default='bi-shield-check', help_text='Bootstrap icon class (e.g. bi-shield-check, bi-cpu, bi-lightning-charge, bi-tools)', max_length=100)),
                ('badge_text', models.CharField(blank=True, help_text="Optional highlight tag, e.g. 'Safety First', 'Eco-Smart'", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display priority')),
                ('active', models.BooleanField(default=True, help_text='Toggle display on the website')),
            ],
            options={
                'verbose_name': 'Why Choose Us Feature',
                'verbose_name_plural': 'Why Choose Us Features',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Bold headline, e.g., 'Next-Generation Vertical Mobility'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text="Accent badge text, e.g., 'ISO 9001:2015 Certified Elevator Solutions'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short narrative detailing engineering standards and client benefits')),
                ('image', models.ImageField(blank=True, help_text='High-resolution hero banner photograph (1920x1080 recommended)', null=True, upload_to='hero/')),
                ('button_text', models.CharField(default='Explore Products', help_text='Primary CTA button label', max_length=50)),
                ('button_url', models.CharField(default='#products', help_text='Primary CTA target URL', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, default='Request A Quote', help_text='Secondary CTA button label', max_length=50)),
                ('secondary_button_url', models.CharField(blank=True, default='#contact', help_text='Secondary CTA target URL', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('active', models.BooleanField(default=True, help_text='Toggle visibility on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Residential High-Rises, Commercial Towers, Hospitals & Healthcare, Luxury Hotels, Industrial Facilities', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Overview of specific vertical transport solutions engineered for this sector')),
                ('icon', models.CharField(default='bi-buildings', help_text='Bootstrap icon class', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Representative sector photography', null=True, upload_to='industries/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('active', models.BooleanField(default=True, help_text='Toggle visibility')),
            ],
            options={
                'verbose_name': 'Industry We Serve',
                'verbose_name_plural': 'Industries We Serve',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Sequence number (1, 2, 3...)')),
                ('title', models.CharField(help_text='e.g. Consultation, Site Survey, Design & Engineering, Manufacturing, Installation, Rigorous Testing, Handover & AMC', max_length=150)),
                ('short_description', models.TextField(help_text='Summary of activities performed in this stage')),
                ('icon', models.CharField(default='bi-gear-wide-connected', help_text='Bootstrap icon class', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sequence order')),
                ('active', models.BooleanField(default=True, help_text='Toggle display')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['step_number', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Krupa Elevator', help_text='Corporate entity name', max_length=150)),
                ('tagline', models.CharField(default='Engineering Precision. Supreme Safety. Elevated Living.', help_text='Brand slogan or tagline', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Primary corporate logo (PNG / SVG recommended)', null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon icon', null=True, upload_to='settings/')),
                ('phone', models.CharField(default='+91 98765 43210', help_text='Primary business phone number', max_length=30)),
                ('alternate_phone', models.CharField(blank=True, default='+91 98765 43211', help_text='Secondary/sales phone number', max_length=30)),
                ('email', models.EmailField(default='info@krupaelevator.com', help_text='Primary contact email address', max_length=254)),
                ('whatsapp', models.CharField(default='+919876543210', help_text='WhatsApp contact number including country code without spaces', max_length=30)),
                ('address', models.TextField(default='Plot No. 42, Engineering Zone, GIDC Industrial Estate, Ahmedabad, Gujarat 382445, India', help_text='Physical factory / corporate office address')),
                ('working_hours', models.CharField(default='Mon - Sat: 9:00 AM - 7:00 PM | 24x7 Breakdown Response', help_text='Operational office & emergency support timings', max_length=150)),
                ('emergency_helpline', models.CharField(default='+91 98765 43210', help_text='Dedicated 24/7 elevator rescue & breakdown hotline', max_length=30)),
                ('google_map_embed', models.TextField(blank=True, help_text='Google Maps iframe HTML or URL embed for contact section')),
                ('facebook', models.URLField(blank=True, help_text='Facebook Page URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram Profile URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn Company Page URL')),
                ('youtube', models.URLField(blank=True, help_text='YouTube Channel URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter / X Profile URL')),
                ('footer_description', models.TextField(blank=True, default='Krupa Elevator is a trusted pioneer in state-of-the-art vertical transport solutions. We specialize in precision engineering, modern passenger lifts, high-capacity freight elevators, and responsive 24/7 maintenance services.', help_text='Descriptive summary displayed in the website footer')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Years of Excellence, Elevators Installed, Happy Clients', max_length=100)),
                ('number', models.CharField(help_text='Metric number value, e.g. 15, 1200, 99', max_length=20)),
                ('suffix', models.CharField(blank=True, default='+', help_text='e.g. +, %, /7', max_length=10)),
                ('icon', models.CharField(default='bi-award', help_text='Bootstrap icon class (e.g. bi-award, bi-building-up, bi-people, bi-geo-alt)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which metric is rendered')),
                ('active', models.BooleanField(default=True, help_text='Toggle display on the homepage')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
