# Generated by Django 5.2.17 on 2026-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client or corporate developer name', max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='Client brand logo', null=True, upload_to='clients/')),
                ('website', models.URLField(blank=True, help_text='Client website URL')),
                ('industry', models.CharField(blank=True, help_text='e.g. Real Estate Developer, Healthcare, IT Park', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief partnership summary or elevator project scope')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client / Partner',
                'verbose_name_plural': 'Clients & Partners',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Service title, e.g. 'Elevator Installation'", max_length=150)),
                ('slug', models.SlugField(help_text="SEO slug, e.g. 'elevator-installation'", max_length=160, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief tagline for cards', max_length=255)),
                ('description', models.TextField(help_text='Detailed service overview, methodology, and commitment')),
                ('icon', models.CharField(default='bi-tools', help_text='Bootstrap Icons class', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Banner/featured photograph', null=True, upload_to='services/')),
                ('features', models.TextField(blank=True, help_text='Service scope, deliverables, or checklist (one per line)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
