# Generated by Django 5.2.17 on 2026-09-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of executive / reviewer', max_length=120)),
                ('client_title', models.CharField(blank=True, help_text='e.g. Managing Director, Chief Engineer, Resident Society Secretary', max_length=150)),
                ('company', models.CharField(blank=True, help_text='e.g. Skyline Developers, Apex Group', max_length=150)),
                ('city', models.CharField(blank=True, help_text='e.g. Ahmedabad, Mumbai, Pune', max_length=100)),
                ('elevator_type_installed', models.CharField(blank=True, help_text='e.g. Dual High-Speed MRL Passenger Lifts', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars')),
                ('quote', models.TextField(help_text='Client review or testimonial text')),
                ('photo', models.ImageField(blank=True, help_text='Client portrait or company representative', null=True, upload_to='testimonials/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=True, help_text='Showcase on homepage carousel')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
