# Generated by Django 5.2.17 on 2026-09-05 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline for article', max_length=220)),
                ('slug', models.SlugField(help_text='SEO URL slug', max_length=240, unique=True)),
                ('author', models.CharField(default='Krupa Engineering Team', max_length=100)),
                ('summary', models.TextField(help_text='Short lead-in summary (2-3 sentences) for index cards')),
                ('content', models.TextField(help_text='Full article narrative, technical breakdown, and engineering insights')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('reading_time', models.PositiveIntegerField(default=4, help_text='Estimated minutes to read')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Pageview counter')),
                ('published_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False, help_text='Highlight as featured hero story')),
                ('active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=220)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
