# Generated by Django 5.2.17 on 2026-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name of the inquirer', max_length=120)),
                ('phone', models.CharField(help_text='Primary Contact / Mobile Number', max_length=25)),
                ('email', models.EmailField(help_text='Email Address', max_length=254)),
                ('company', models.CharField(blank=True, help_text='Company / Firm Name (Optional)', max_length=150)),
                ('city', models.CharField(help_text='City / Location', max_length=100)),
                ('subject', models.CharField(blank=True, help_text='Subject / Purpose of inquiry', max_length=200)),
                ('message', models.TextField(help_text='Message / Requirements')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Follow Up', 'Follow Up'), ('Converted', 'Converted'), ('Closed', 'Closed')], db_index=True, default='New', help_text='Current lead processing status', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal sales/executive notes on follow-up calls or client remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Full Name of the contact person', max_length=120)),
                ('company_name', models.CharField(blank=True, help_text='Builder, Architect, or Company Name', max_length=150)),
                ('phone', models.CharField(help_text='Contact Phone Number', max_length=25)),
                ('email', models.EmailField(help_text='Email Address for sending quotation PDF', max_length=254)),
                ('city', models.CharField(db_index=True, help_text='City where project is located', max_length=100)),
                ('project_location', models.CharField(blank=True, help_text='Locality, site address or landmark', max_length=255)),
                ('building_type', models.CharField(choices=[('Residential Apartment', 'Residential Apartment / Society'), ('Private Villa / Bungalow', 'Private Villa / Bungalow'), ('Commercial / Corporate Office', 'Commercial / Corporate Office'), ('Hospital / Healthcare', 'Hospital / Healthcare Facility'), ('Hotel / Hospitality', 'Hotel / Hospitality Resort'), ('Industrial / Factory / Warehouse', 'Industrial / Factory / Warehouse'), ('Mall / Retail Showroom', 'Mall / Retail Showroom'), ('Educational / Institution', 'Educational / Institution'), ('Other', 'Other Structure')], db_index=True, max_length=60)),
                ('elevator_type', models.CharField(choices=[('Passenger Elevator', 'Passenger Elevator (Gearless / Geared)'), ('Home / Villa Elevator', 'Home / Villa Elevator (Compact / Pitless)'), ('Hospital Stretcher Elevator', 'Hospital Stretcher Elevator (Bed Lift)'), ('Freight / Goods Elevator', 'Freight / Goods Elevator (Heavy Duty)'), ('Panoramic Glass Elevator', 'Panoramic Glass Elevator (Capsule / Scenic)'), ('Hydraulic Elevator', 'Hydraulic Elevator'), ('MRL Elevator', 'Machine Room-Less (MRL) Elevator'), ('Dumbwaiter', 'Dumbwaiter / Food Lift'), ('Escalator / Moving Walkway', 'Commercial Escalator / Moving Walkway'), ('Modernization / AMC', 'Elevator Modernization / AMC'), ('Other', 'Other Elevator System')], db_index=True, max_length=60)),
                ('number_of_floors', models.CharField(help_text='e.g. G+4 Floors, 10 Stops, Basement + Ground + 3', max_length=50)),
                ('capacity_required', models.CharField(blank=True, default='8 Passengers / 544 kg', help_text='e.g. 6 Passengers / 408 kg, 8 Passengers / 544 kg, 13 Passengers / 884 kg, 1000 kg Stretcher, 2 Ton Goods', max_length=100)),
                ('number_of_elevators', models.PositiveIntegerField(default=1, help_text='Number of elevator units needed')),
                ('project_stage', models.CharField(blank=True, choices=[('Architectural Planning', 'Architectural Planning / Blueprints Stage'), ('Civil Construction Ongoing', 'Civil Construction Ongoing (Shaft Under Build)'), ('Civil Hoistway Ready', 'Civil Hoistway Ready for Elevator Installation'), ('Modernization / Replacement', 'Modernization / Replacement of Existing Lift'), ('Urgent Requirement', 'Immediate / Urgent Requirement')], default='Civil Construction Ongoing', max_length=60)),
                ('message', models.TextField(blank=True, help_text='Specific requirements: cabin finishes, door types, speed, shaft dimensions, or special remarks')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Survey Scheduled', 'Survey Scheduled'), ('Quotation Sent', 'Quotation Sent'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], db_index=True, default='New', help_text='Current pipeline stage', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal sales estimation notes, survey findings, proposal price and date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
