# Generated by Django 5.2.17 on 2026-09-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name, e.g. 'Passenger Elevator'", max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='SEO-friendly URL identifier', max_length=160, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief tagline or summary for cards and menus', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed category overview explaining engineering and use cases')),
                ('image', models.ImageField(blank=True, help_text='Thumbnail image for category grids and preview cards', null=True, upload_to='categories/')),
                ('banner_image', models.ImageField(blank=True, help_text='Header banner image for category landing pages', null=True, upload_to='categories/banners/')),
                ('icon', models.CharField(default='bi-building', help_text='Bootstrap Icons class (e.g. bi-person-walking, bi-hospital, bi-house-heart)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordering priority in menus and lists')),
                ('active', models.BooleanField(default=True, help_text='Toggle visibility across website and navbar')),
                ('meta_title', models.CharField(blank=True, help_text='Custom HTML title for SEO', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Model / Product name (e.g. 'Standard Passenger Elevator')", max_length=180)),
                ('slug', models.SlugField(help_text='SEO-friendly URL identifier', max_length=190, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Concise product overview for catalog cards', max_length=350)),
                ('description', models.TextField(help_text='Comprehensive product description, architecture, and technology')),
                ('featured_image', models.ImageField(blank=True, help_text='Primary product photograph for catalog and detail hero', null=True, upload_to='products/featured/')),
                ('capacity', models.CharField(blank=True, help_text='e.g. 4 to 26 Passengers (320 kg - 2000 kg)', max_length=120)),
                ('speed', models.CharField(blank=True, help_text='e.g. 0.65 m/s to 2.5 m/s', max_length=100)),
                ('number_of_stops', models.CharField(blank=True, help_text='e.g. Up to 35 Floors (G+34)', max_length=100)),
                ('drive_type', models.CharField(blank=True, help_text='e.g. Regenerative V3F Microprocessor Controller', max_length=120)),
                ('machine_type', models.CharField(blank=True, help_text='e.g. Gearless PMSM / Geared Traction', max_length=120)),
                ('door_type', models.CharField(blank=True, help_text='e.g. Center Opening / Side Opening Telescopic Automatic', max_length=120)),
                ('application', models.CharField(blank=True, help_text='e.g. Residential High-Rises, Commercial Towers, Hotels', max_length=150)),
                ('pit_depth', models.CharField(blank=True, default='Min. 1400 mm', help_text='Minimum hoistway pit depth requirement', max_length=100)),
                ('overhead', models.CharField(blank=True, default='Min. 4200 mm', help_text='Minimum clear overhead clearance requirement', max_length=100)),
                ('power_supply', models.CharField(blank=True, default='415V, 3-Phase, 50Hz (Single-Phase option available)', help_text='Electrical power requirements', max_length=100)),
                ('features', models.TextField(blank=True, help_text='Key features and safety mechanisms (one item per line)')),
                ('technical_specifications', models.TextField(blank=True, help_text="Additional specifications in 'Key: Value' format (one per line)")),
                ('finishes', models.TextField(blank=True, help_text='Available cabin interior finishes and decorative styles (one per line)')),
                ('brochure', models.FileField(blank=True, help_text='Upload technical brochure (PDF format recommended)', null=True, upload_to='products/brochures/')),
                ('featured', models.BooleanField(default=False, help_text='Highlight on homepage or top catalog section')),
                ('active', models.BooleanField(default=True, help_text='Toggle product visibility')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display sequence')),
                ('meta_title', models.CharField(blank=True, help_text='Custom HTML page title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Elevator Product',
                'verbose_name_plural': 'Elevator Products',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image photograph', upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional description for lightbox and alt tag', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in product gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Gallery Image',
                'verbose_name_plural': 'Product Gallery Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
